ALS-1523
aml-org/als pull request #562
Opened 2021-06-29 21:11 UTC by emilianoascona

Addgin tests for YNodeBranchBuilder and creating YamlWrapperTest suite with both editionMode T and F

2021-06-29 22:47 UTC, llibarona requested changes

2021-06-29 22:47 UTC, llibarona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YNodeBranchBuilderTest.scala
> +    assert(branch.node.isInstanceOf[YMap])
no entiendo que estas asserteando aca
un YMap va a ser tanto el root, como A, como B

2021-06-29 22:47 UTC, llibarona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YNodeBranchBuilderTest.scala
> +    assert(branch.node.isInstanceOf[YMap])
aca va a haber mas de un YMap, tenes que desambiguar si es el root o "a"

2021-06-29 22:47 UTC, llibarona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YNodeBranchBuilderTest.scala
> +    cBranch.isInArray should be(true)
falta probar las posiciones de subkey3 puede ser? (el array inflow)

2021-06-29 22:47 UTC, llibarona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YNodeBranchBuilderTest.scala
> +  test("") {
te olvidaste el nombre del test?

2021-06-29 22:47 UTC, llibarona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YNodeBranchBuilderTest.scala
> +    val l2BrotherBranch = NodeBranchBuilder.build(root, l2Brother, isJson = false)
tambien las assertions?

2021-06-29 22:47 UTC, llibarona commented on als-suggestions/shared/src/test/resources/test/json/json-begin-mapping.json
> +      "get": {
creo que el espacio este no deberia estar, raro que el scala formatter no te lo haya quitado al commitear

2021-06-29 22:47 UTC, llibarona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YamlWrapperTest.scala
> +  ignore("Empty map entry inflow") {
los ignore son los que estan dando incorrecto, verdad?

2021-06-29 22:47 UTC, llibarona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YamlWrapperTest.scala
> +  test("Check inside indented flowMap") {
por legibilidad, podras agrupar los tests con cada string que testean?
creo que una forma mas legible seria usar `FlatSpec` y estructurar estilo:

```
behavior of "flow cases"

it should "check inside indented flow map" in {}
```

(un ejemplo de este tipo de tests esta en `org.mulesoft.als.common.objectintree.ObjectInTreeArraysTests`, para este caso no necesitas que sea `Async`)

2021-06-30 00:01 UTC, llibarona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/FlatAstBuilder.scala
> +  def getNodesQuantity() = flatCase.size
medio verbose, podria ser `length` o `size` o algo asi?

2021-06-30 00:02 UTC, llibarona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/FlatAstBuilder.scala
> +  def getNodesQuantityForPosition(position: AmfPosition, editionMode: Boolean = true): Int =
creo que con `nodesForPosition(..).size` queda mas claro y menos verbose, puede ser?

2021-06-30 00:05 UTC, llibarona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YamlWrapperTest.scala
> +    assert(nodes.getNodesQuantity() == 61)
este assertion no se si sirve para mucho, lo que si interesaria es revisar que la cantidad de nodos que matchean con cada posicion es la indicada (podes checkear por cantidad y manualmente revisas que de verdad sean todos los esperados cuando haces el test)

2021-06-30 00:08 UTC, llibarona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YamlWrapperTest.scala
> +    nodes.assertDiffEditionMode(AmfPosition(2, 2))
falto el `assert()`?

2021-06-30 00:08 UTC, llibarona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/FlatAstBuilder.scala
> +  def assertDiffEditionMode(position: AmfPosition): Boolean =
no veo casos en los que de distinto, si nunca damos resultados distintos entonces no deberia existir el edition mode
si hay casos en los que da distinto deberia haber tests para asegurarnos (en ese test ademas del `!assertDiffEditionMode(...)` tambien habria que revisar los deltas de uno con otro)

2021-06-30 03:02 UTC, emilianoascona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YNodeBranchBuilderTest.scala
> +    cBranch.isInArray should be(true)
si, ya lo agregue

2021-06-30 03:03 UTC, emilianoascona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YNodeBranchBuilderTest.scala
> +  test("") {
evidentemente, si.

2021-06-30 03:07 UTC, emilianoascona commented on als-suggestions/shared/src/test/resources/test/json/json-begin-mapping.json
> +      "get": {
quitado

2021-06-30 03:29 UTC, emilianoascona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YNodeBranchBuilderTest.scala
> +    val l2BrotherBranch = NodeBranchBuilder.build(root, l2Brother, isJson = false)
si. Al final este caso iba a ser pruebas con distintas indentaciones pero lo termine haciendo en el anterior asi que este lo saco porque quedaria redundante

2021-06-30 03:30 UTC, emilianoascona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YamlWrapperTest.scala
> +  ignore("Empty map entry inflow") {
right

2021-06-30 12:23 UTC, agusayerza commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YNodeBranchBuilderTest.scala
> +    assert(aBranch.brothersKeys.contains("param1"))
Puede ser que el nombre del test no coincide con el assertion? Estamos detectando brothers cuando deberiamos assertear indentation?

2021-06-30 12:50 UTC, emilianoascona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/FlatAstBuilder.scala
> +  def getNodesQuantity() = flatCase.size
right

2021-06-30 15:07 UTC, emilianoascona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/FlatAstBuilder.scala
> +  def getNodesQuantity() = flatCase.size
done

2021-06-30 15:07 UTC, emilianoascona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/FlatAstBuilder.scala
> +  def getNodesQuantityForPosition(position: AmfPosition, editionMode: Boolean = true): Int =
si, ya lo modifique

2021-06-30 15:07 UTC, emilianoascona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YamlWrapperTest.scala
> +    nodes.assertDiffEditionMode(AmfPosition(2, 2))
claramente

2021-06-30 15:45 UTC, emilianoascona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/FlatAstBuilder.scala
> +  def assertDiffEditionMode(position: AmfPosition): Boolean =
hay uno de los casos que estan ignorados en los que esta la diferencia, pero justamente al estar ignorados no lo estamos contemplando ahora

2021-06-30 17:31 UTC, emilianoascona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YNodeBranchBuilderTest.scala
> +    assert(aBranch.brothersKeys.contains("param1"))
la idea el test es detectar si estoy bien parado en el arbol en distintas indentaciones y distintas alturas, y para eso chequeo contra los hermanos como "pivotes"

2021-06-30 17:46 UTC, emilianoascona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YamlWrapperTest.scala
> +    assert(nodes.getNodesQuantity() == 61)
agregue un test puntual para validar la cantidad de nodos esperada

2021-06-30 19:49 UTC, emilianoascona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/YNodeBranchBuilderTest.scala
> +    assert(branch.node.isInstanceOf[YMap])
done

2021-07-05 13:41 UTC, llibarona submitted a review, later dismissed

2021-07-05 13:43 UTC, agusayerza submitted a review, later dismissed

2021-07-05 13:54 UTC, agusayerza approved these changes

2021-07-05 13:59 UTC, merged