Fixing bug with suggestions ALS-1437
aml-org/als pull request #570
Opened 2021-07-23 17:20 UTC by emilianoascona

2021-07-23 20:10 UTC, llibarona requested changes

2021-07-23 20:10 UTC, llibarona commented on als-common/shared/src/main/scala/org/mulesoft/als/common/YamlWrapper.scala
> +          !isJson && editionMode && m.respectIndentation(amfPosition)
junto con el !isJson habria que validar que no este inflow?

2021-07-23 20:10 UTC, llibarona commented on als-common/shared/src/main/scala/org/mulesoft/als/common/YamlWrapper.scala
> +        case p => p.contains(amfPosition, editionMode)
esto ya se valida arriba en el `or` no?

2021-07-26 15:13 UTC, llibarona requested changes

2021-07-26 15:13 UTC, llibarona commented on als-actions/shared/src/test/resources/actions/hover/async-api20-full-result.yaml
> +  (34,13): []
no deberia haber desaparecido, con que matchea ahora? (busca el amfObject con el que entra para ese rango)

2021-07-26 15:13 UTC, llibarona commented on als-actions/shared/src/test/resources/actions/hover/async-api20-full-result.yaml
> +    - Action that can be executed using a particular HTTP invocation
antes matcheaba con uno mas especifico, por que ahora matchea con un padre?

2021-07-26 15:13 UTC, llibarona commented on als-actions/shared/src/test/resources/actions/hover/async-api20-full-result.yaml
> +  (44,15): []
mismo que el primero

2021-07-26 15:13 UTC, llibarona commented on als-actions/shared/src/test/resources/actions/hover/async-api20-full-result.yaml
> +  (62,15): []
mismo que el primero (aparentemente todos los `$ref` estan perdiendose)

2021-07-27 19:15 UTC, emilianoascona commented on als-common/shared/src/main/scala/org/mulesoft/als/common/AmfSonElementFinder.scala
> +    case class SonFinder(location: String, definedBy: Dialect, amfPosition: AmfPosition, yPartBranch: YPartBranch) {
La posicion se sigue usando para algunas funciones de la clase.

2021-07-27 19:16 UTC, emilianoascona commented on als-common/shared/src/main/scala/org/mulesoft/als/common/AmfSonElementFinder.scala
> +                if (!a.obj.containsPosition(yPartBranch) && b.obj.containsPosition(yPartBranch)) b else a // most specific
renamed

2021-07-27 19:16 UTC, emilianoascona commented on als-common/shared/src/main/scala/org/mulesoft/als/common/YamlWrapper.scala
> +        case p => p.contains(amfPosition, editionMode)
si. Saque la validacion y devuelvo false por defecto

2021-07-27 19:17 UTC, emilianoascona commented on als-actions/shared/src/test/resources/actions/hover/async-api20-full-result.yaml
> +    - Action that can be executed using a particular HTTP invocation
creo el bug para hover

2021-07-27 19:17 UTC, emilianoascona commented on als-actions/shared/src/test/resources/actions/hover/async-api20-full-result.yaml
> +  (44,15): []
creo el bug para hover para revisarlo

2021-07-27 19:32 UTC, llibarona commented on als-common/shared/src/main/scala/org/mulesoft/als/common/AmfSonElementFinder.scala
> +    case class SonFinder(location: String, definedBy: Dialect, amfPosition: AmfPosition, yPartBranch: YPartBranch) {
no se puede usar la yPartBranch.position donde sea necesaria? (en lugar de pasar ademas tambien la amfPosition)

2021-07-27 20:36 UTC, llibarona approved these changes

2021-07-27 21:54 UTC, agusayerza approved these changes

2021-07-28 12:07 UTC, merged