Adding hotReloadDialect option as InitParam ALS-1725
aml-org/als pull request #640
Opened 2021-10-25 20:08 UTC by emilianoascona

2021-11-08 21:27 UTC, llibarona requested changes

2021-11-08 21:27 UTC, llibarona commented on als-server/shared/src/main/scala/org/mulesoft/als/server/workspace/WorkspaceManager.scala
> +                                  configurationManager: ConfigurationManager)
Configuration Provider instead? or do we need manager?

2021-11-08 21:27 UTC, llibarona commented on als-server/shared/src/test/scala/org/mulesoft/als/server/textsync/DialectRegistryTest.scala
> +  test("Remove old dialect after modifying it") {
is this the only test? maybe add some more, changing dialects, version/name, properties, etc
asserting there are no duplicated dialects registered and that the last one is the registered at the end

2021-11-18 15:52 UTC, llibarona approved these changes

2021-11-18 16:45 UTC, agusayerza approved these changes

2021-11-18 17:33 UTC, merged