W-11138673: Added version validation for uses facet in AMLPathCompletionPlugin.scala
aml-org/als pull request #759
Opened 2022-05-23 13:50 UTC by mansillafederico

[W-11138673](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000wwLrTYAU/view):Invalid path suggestions for uses in RAML 0.8

2022-05-23 20:44 UTC, emilianoascona commented on als-common/shared/src/main/scala/org/mulesoft/amfintegration/dialect/DialectKnowledge.scala
> +  def isPathFacetSupportedByVersion(spec: Spec): Boolean =
podrias hacer un Option para el parametro de entrada y ahi validar la spec para evitar el getOrElse

2022-05-23 20:44 UTC, emilianoascona commented on als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/AMLPathCompletionPlugin.scala
> +      )) && DialectKnowledge.isPathFacetSupportedByVersion(params.baseUnit.sourceSpec.getOrElse(""))
este getOrElse no es compatible con la firma de la funcion que armaste (espera un parametro e tipo Spec y le mandas un string)

2022-05-26 13:23 UTC, llibarona requested changes

2022-05-26 13:23 UTC, llibarona commented on als-suggestions/shared/src/test/resources/test/raml10/by-directory/top-level/expected/uses.raml.json
> +[
entiendo que el golden deberia venir vacio para raml 0.8 porque no soporta uses

2022-05-26 13:23 UTC, llibarona commented on als-suggestions/shared/src/test/resources/test/raml08/by-directory/top-level/uses.raml
> +  file: !include *
en caso de uses, el path va directo (sin el !include)

2022-05-26 13:23 UTC, llibarona commented on als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/AMLPathCompletionPlugin.scala
>    override def resolve(params: AmlCompletionRequest): Future[Seq[RawSuggestion]] =
`AMLLibraryPathCompletion` es el plugin que ataja estos casos, checkear si lo mas facil es quitarlo de `AMLBaseCompletionPlugins` y en su lugar agregarlo a `RamlCompletionPluginRegistry`

2022-05-26 13:23 UTC, emilianoascona commented on als-suggestions/shared/src/main/scala/org/mulesoft/als/suggestions/plugins/aml/AMLPathCompletionPlugin.scala
> +      )) && DialectKnowledge.isPathFacetSupportedByVersion(params.baseUnit.sourceSpec)
me parece que queda mas facil de leer si agregas esta validacion junto con la de isRamlInclusion.
algo como ((isRamlInclusion && isPathFacetSupportedByVersion) || isJsonInclusion)

2022-05-26 13:26 UTC, llibarona commented on als-suggestions/shared/src/test/resources/test/raml10/by-directory/top-level/uses.raml
> +  file: !include *
en RAML 1.0 ya existe el test: `als-suggestions/shared/src/test/resources/test/raml10/by-directory/libraries/uses.raml`
bastaria con agregar el de RAML 0.8 con el golden vacio

2022-05-26 20:06 UTC, closed without merging