W-13784661/Improve logging
aml-org/als pull request #951
Opened 2023-08-10 20:23 UTC by mansillafederico

- W-13784661: Logger refactor

2023-08-11 21:23 UTC, llibarona requested changes

2023-08-11 21:23 UTC, llibarona commented on als-server/shared/src/main/scala/org/mulesoft/als/server/modules/diagnostic/ResolutionDiagnosticManager.scala
> +    Logger.debug("Got new AST:\n" + resolved.baseUnit.id, "ResolutionDiagnosticManager", "newASTAvailable")
de vuelta, los multilines no los queremos

2023-08-11 21:23 UTC, llibarona commented on als-server/shared/src/main/scala/org/mulesoft/als/server/modules/diagnostic/ResolutionDiagnosticManager.scala
> +    Logger.error(s"Error on validation: ${exception.toString}", "ResolutionDiagnosticManager", "newASTAvailable")
probablemente quede mejor el getMessage

2023-08-11 21:23 UTC, llibarona commented on als-server/shared/src/main/scala/org/mulesoft/als/server/modules/diagnostic/custom/CustomValidationManager.scala
>        "Running custom validations on:\n" + resolved.baseUnit.id,
de vuelta, log multiline

2023-08-11 21:23 UTC, llibarona commented on als-server/shared/src/test/scala/org/mulesoft/als/server/FailedLogs.scala
> +object TestLogger {
por que creaste el object? no es lo mismo que tener un private final static val newLine o algo asi?

2023-08-11 21:23 UTC, llibarona commented on als-server/shared/src/test/scala/org/mulesoft/als/server/LoggerTestConfiguration.scala
> +trait LoggerTestConfiguration extends AsyncFunSuite with BeforeAndAfterEach {
si no vas a usar ninguna feature de TestLogger entonces en vez de crearlo y limpiarlo cada vuelta podes usar EmptyLogger en los tests

2023-08-11 21:23 UTC, llibarona commented on als-server/shared/src/test/scala/org/mulesoft/als/server/errorhandler/ErrorHandlingTest.scala
> +    logger.cleanLogList()
se usan para algo los logs antes de limpiralos? si no se usan entonces en lugar de hacer esto se puede setear el EmptyLogger

2023-08-11 21:23 UTC, llibarona commented on als-server/shared/src/test/scala/org/mulesoft/als/server/stagingarea/parser/ParserStagingAreaTests.scala
> +//  class TestLogger extends Logger {
para que dejar bloques comentados?

2023-08-11 21:23 UTC, llibarona commented on als-common/shared/src/test/scala/org/mulesoft/als/common/MarkerFinderTest.scala
> +    Logger.withLogger(EmptyLogger)
me hace muchisimo ruido el scope tan chico en el cual haces estos withLoggers, antes donde lo recibia esto? probablemente los `withLogger` los debas hacer en los lugares donde antes se creaban los loggers (TestLogger donde corresponda, EmptyLogger donde ya este pasando ese, no usemos indiscriminadamente el `withLogger` en cualquier parte porque vamos a perder los logs cuando falla un test)

en LanguageServerBaseTest setea un fixture que crea un TestLogger y despues loggerFixture se encarga de limpiarlo antes de correr el test y despues de los tests, y ese logger se printea cuando hay un error
si nosotros estamos cambiando los logs por dentro de ese codigo entonces vamos a perder traces

2023-08-11 21:23 UTC, llibarona commented on als-server/shared/src/main/scala/org/mulesoft/als/server/modules/actions/CodeActionManager.scala
> +    Logger.debug(s"actions to be used:\n${usedActions.map(_.title).mkString("\n")}", "CodeActionManager", "applyConfig")
multilines, se ven feos en los logs

2023-08-11 21:32 UTC, mansillafederico commented on als-server/shared/src/main/scala/org/mulesoft/als/server/modules/diagnostic/DiagnosticManager.scala
>        s"Number of ${step.name} errors is:\n" + errors.flatMap(_.issues).length,
Genial, me parece bien. Los llevo al formato que usa Log4j por defecto a ver si les copa como queda.

2023-08-11 21:34 UTC, mansillafederico commented on als-server/shared/src/test/scala/org/mulesoft/als/server/LoggerTestConfiguration.scala
> +trait LoggerTestConfiguration extends AsyncFunSuite with BeforeAndAfterEach {
Es verdad, en casi todos lados metí el empty logger pero hubo muchos tests que usan el log para los asserts por eso cree esto, para no repetir código.

2023-08-11 21:35 UTC, mansillafederico commented on als-server/shared/src/test/scala/org/mulesoft/als/server/errorhandler/ErrorHandlingTest.scala
> +    logger.cleanLogList()
Si, hay 4 tests en esta clase que usan el log para los asserts.

2023-08-11 21:36 UTC, mansillafederico commented on als-server/shared/src/test/scala/org/mulesoft/als/server/stagingarea/parser/ParserStagingAreaTests.scala
> +//  class TestLogger extends Logger {
Mala mia

2023-08-14 13:40 UTC, mansillafederico commented on als-server/shared/src/main/scala/org/mulesoft/als/server/modules/diagnostic/ParseDiagnosticManager.scala
> +      Logger.error("Error on validation: " + exception.toString, "ParseDiagnosticManager", "newASTAvailable")
Done

2023-08-14 14:30 UTC, mansillafederico commented on als-server/shared/src/test/scala/org/mulesoft/als/server/FailedLogs.scala
> +object TestLogger {
Fue para no ponerlo público dentro de testLogger porque se utiliza también en ParserStagingAreaTest. Si decís que es mejor que sea _public final static val_ lo cambio

2023-08-14 14:30 UTC, mansillafederico commented on als-server/shared/src/test/scala/org/mulesoft/als/server/FailedLogs.scala
> +object TestLogger {
Esa clase es una de esas que tiene asserts sobre tests

2023-08-14 15:26 UTC, mansillafederico commented on als-common/shared/src/test/scala/org/mulesoft/als/common/MarkerFinderTest.scala
> +    Logger.withLogger(EmptyLogger)
Lean si querés hacemos una call para hablar y avanzar más rápido con este tema. Me complicó mucho reemplazar el TestLogger o EmptyLogger porque se lo pasaba por parámetro en todos las suites de Tests, por eso opté por usar el withLogger.

2023-08-18 21:30 UTC, mansillafederico commented on als-common/shared/src/test/scala/org/mulesoft/als/common/MarkerFinderTest.scala
> +    Logger.withLogger(EmptyLogger)
Conversado en slack

2023-08-22 15:13 UTC, llibarona approved these changes

2023-08-22 16:53 UTC, merged